"""Added canonicalised facilities.

Revision ID: 0d26d554ace9
Revises: 5ca247eca1bd
Create Date: 2018-08-24 12:19:58.909347

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0d26d554ace9'
down_revision = '5ca247eca1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities_canonical',
    sa.Column('facility_canonical_id', sa.BigInteger(), nullable=False),
    sa.Column('google_place_id', sa.Unicode(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('google_url', sa.UnicodeText(), nullable=False),
    sa.Column('url', sa.UnicodeText(), nullable=True),
    sa.Column('address', sa.UnicodeText(), nullable=True),
    sa.Column('phone_number', sa.UnicodeText(), nullable=True),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), nullable=False),
    sa.Column('country', sa.Unicode(), nullable=False),
    sa.Column('administrative_area_level_1', sa.Unicode(), nullable=True),
    sa.Column('administrative_area_level_2', sa.Unicode(), nullable=True),
    sa.Column('administrative_area_level_3', sa.Unicode(), nullable=True),
    sa.Column('administrative_area_level_4', sa.Unicode(), nullable=True),
    sa.Column('administrative_area_level_5', sa.Unicode(), nullable=True),
    sa.Column('locality', sa.Unicode(), nullable=True),
    sa.Column('sublocality', sa.Unicode(), nullable=True),
    sa.Column('sublocality_level_1', sa.Unicode(), nullable=True),
    sa.Column('sublocality_level_2', sa.Unicode(), nullable=True),
    sa.Column('sublocality_level_3', sa.Unicode(), nullable=True),
    sa.Column('sublocality_level_4', sa.Unicode(), nullable=True),
    sa.Column('sublocality_level_5', sa.Unicode(), nullable=True),
    sa.Column('colloquial_area', sa.Unicode(), nullable=True),
    sa.Column('floor', sa.Unicode(), nullable=True),
    sa.Column('room', sa.Unicode(), nullable=True),
    sa.Column('intersection', sa.Unicode(), nullable=True),
    sa.Column('neighborhood', sa.Unicode(), nullable=True),
    sa.Column('post_box', sa.Unicode(), nullable=True),
    sa.Column('postal_code', sa.Unicode(), nullable=True),
    sa.Column('postal_code_prefix', sa.Unicode(), nullable=True),
    sa.Column('postal_code_suffix', sa.Unicode(), nullable=True),
    sa.Column('postal_town', sa.Unicode(), nullable=True),
    sa.Column('premise', sa.Unicode(), nullable=True),
    sa.Column('subpremise', sa.Unicode(), nullable=True),
    sa.Column('route', sa.Unicode(), nullable=True),
    sa.Column('street_address', sa.Unicode(), nullable=True),
    sa.Column('street_number', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('facility_canonical_id', name=op.f('pk_facilities_canonical')),
    schema='clinicaltrials'
    )
    op.create_index(op.f('ix_clinicaltrials_facilities_canonical_administrative_area_level_1'), 'facilities_canonical', ['administrative_area_level_1'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_facilities_canonical_country'), 'facilities_canonical', ['country'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_facilities_canonical_google_place_id'), 'facilities_canonical', ['google_place_id'], unique=True, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_facilities_canonical_locality'), 'facilities_canonical', ['locality'], unique=False, schema='clinicaltrials')
    op.create_table('study_facilities',
    sa.Column('study_facility_id', sa.BigInteger(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.Column('facility_id', sa.BigInteger(), nullable=False),
    sa.Column('facility_canonical_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['facility_canonical_id'], ['clinicaltrials.facilities_canonical.facility_canonical_id'], name=op.f('fk_study_facilities_facility_canonical_id_facilities_canonical')),
    sa.ForeignKeyConstraint(['facility_id'], ['clinicaltrials.facilities.facility_id'], name=op.f('fk_study_facilities_facility_id_facilities')),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_study_facilities_study_id_studies')),
    sa.PrimaryKeyConstraint('study_facility_id', name=op.f('pk_study_facilities')),
    sa.UniqueConstraint('study_id', 'facility_id', name=op.f('uq_study_facilities_study_id')),
    schema='clinicaltrials'
    )
    op.add_column('facilities', sa.Column('facility_canonical_id', sa.BigInteger(), nullable=True), schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_facilities_city'), 'facilities', ['city'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_facilities_country'), 'facilities', ['country'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_facilities_state'), 'facilities', ['state'], unique=False, schema='clinicaltrials')
    op.create_foreign_key(op.f('fk_facilities_facility_canonical_id_facilities_canonical'), 'facilities', 'facilities_canonical', ['facility_canonical_id'], ['facility_canonical_id'], source_schema='clinicaltrials', referent_schema='clinicaltrials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_facilities_facility_canonical_id_facilities_canonical'), 'facilities', schema='clinicaltrials', type_='foreignkey')
    op.drop_index(op.f('ix_clinicaltrials_facilities_state'), table_name='facilities', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_facilities_country'), table_name='facilities', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_facilities_city'), table_name='facilities', schema='clinicaltrials')
    op.drop_column('facilities', 'facility_canonical_id', schema='clinicaltrials')
    op.drop_table('study_facilities', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_facilities_canonical_locality'), table_name='facilities_canonical', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_facilities_canonical_google_place_id'), table_name='facilities_canonical', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_facilities_canonical_country'), table_name='facilities_canonical', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_facilities_canonical_administrative_area_level_1'), table_name='facilities_canonical', schema='clinicaltrials')
    op.drop_table('facilities_canonical', schema='clinicaltrials')
    # ### end Alembic commands ###
