"""Added indices.

Revision ID: 29cdcb008393
Revises: 0d26d554ace9
Create Date: 2018-08-27 21:37:47.016196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cdcb008393'
down_revision = '0d26d554ace9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clinicaltrials_eligibilities_gender'), 'eligibilities', ['gender'], unique=False, schema='clinicaltrials')
    op.drop_index('idx_facilities_canonical_coordinates', table_name='facilities_canonical', schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_studies_start_date'), 'studies', ['start_date'], unique=False, schema='clinicaltrials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_clinicaltrials_studies_start_date'), table_name='studies', schema='clinicaltrials')
    op.create_index('idx_facilities_canonical_coordinates', 'facilities_canonical', ['coordinates'], unique=False, schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_eligibilities_gender'), table_name='eligibilities', schema='clinicaltrials')
    # ### end Alembic commands ###
