"""added supplemental-synonyms table.

Revision ID: 2f06a908dd0a
Revises: 8d5bf8037420
Create Date: 2018-06-12 10:27:52.447423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f06a908dd0a'
down_revision = '8d5bf8037420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplemental_synonyms',
    sa.Column('supplemental_synonym_id', sa.BigInteger(), nullable=False),
    sa.Column('supplemental_id', sa.BigInteger(), nullable=False),
    sa.Column('synonym', sa.Unicode(), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.ForeignKeyConstraint(['supplemental_id'], ['mesh.supplementals.supplemental_id'], name=op.f('fk_supplemental_synonyms_supplemental_id_supplementals')),
    sa.PrimaryKeyConstraint('supplemental_synonym_id', name=op.f('pk_supplemental_synonyms')),
    sa.UniqueConstraint('supplemental_id', 'md5', name=op.f('uq_supplemental_synonyms_supplemental_id')),
    schema='mesh'
    )
    op.create_index(op.f('ix_mesh_supplemental_synonyms_md5'), 'supplemental_synonyms', ['md5'], unique=False, schema='mesh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mesh_supplemental_synonyms_md5'), table_name='supplemental_synonyms', schema='mesh')
    op.drop_table('supplemental_synonyms', schema='mesh')
    # ### end Alembic commands ###
