"""md5 field in definitions tables

Revision ID: 3c99f122a48c
Revises: 90684829fdc2
Create Date: 2018-11-10 21:52:01.090978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c99f122a48c'
down_revision = '90684829fdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descriptor_definitions', sa.Column('md5', sa.LargeBinary(length=16), nullable=False), schema='mesh')
    op.create_index(op.f('ix_mesh_descriptor_definitions_md5'), 'descriptor_definitions', ['md5'], unique=False, schema='mesh')
    op.drop_constraint('uq_descriptor_definitions_descriptor_id', 'descriptor_definitions', schema='mesh', type_='unique')
    op.create_unique_constraint(op.f('uq_descriptor_definitions_descriptor_id'), 'descriptor_definitions', ['descriptor_id', 'source', 'md5'], schema='mesh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_descriptor_definitions_descriptor_id'), 'descriptor_definitions', schema='mesh', type_='unique')
    op.create_unique_constraint('uq_descriptor_definitions_descriptor_id', 'descriptor_definitions', ['descriptor_id', 'source'], schema='mesh')
    op.drop_index(op.f('ix_mesh_descriptor_definitions_md5'), table_name='descriptor_definitions', schema='mesh')
    op.drop_column('descriptor_definitions', 'md5', schema='mesh')
    # ### end Alembic commands ###
