"""added app schema with basic user-data tables

Revision ID: 44cd6e323356
Revises: a587cf021d1c
Create Date: 2018-10-21 09:00:41.990349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44cd6e323356'
down_revision = 'a587cf021d1c'
branch_labels = None
depends_on = None


gender_enum = postgresql.ENUM('FEMALE', 'MALE', 'ALL', name='gendertype', create_type=False)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searches',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('search_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=False),
    sa.Column('gender', gender_enum, nullable=True),
    sa.Column('year_beg', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('age_beg', sa.Integer(), nullable=True),
    sa.Column('age_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('search_id', name=op.f('pk_searches')),
    sa.UniqueConstraint('search_uuid', name=op.f('uq_searches_search_uuid')),
    schema='app'
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auth0_user_id', sa.Unicode(), nullable=False),
    sa.Column('email', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('auth0_user_id', name=op.f('uq_users_auth0_user_id')),
    schema='app'
    )
    op.create_table('search_descriptors',
    sa.Column('search_descriptor_id', sa.BigInteger(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('descriptor_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['descriptor_id'], ['mesh.descriptors.descriptor_id'], name=op.f('fk_search_descriptors_descriptor_id_descriptors')),
    sa.ForeignKeyConstraint(['search_id'], ['app.searches.search_id'], name=op.f('fk_search_descriptors_search_id_searches')),
    sa.PrimaryKeyConstraint('search_descriptor_id', name=op.f('pk_search_descriptors')),
    sa.UniqueConstraint('search_id', 'descriptor_id', name=op.f('uq_search_descriptors_search_id')),
    schema='app'
    )
    op.create_index(op.f('ix_app_search_descriptors_descriptor_id'), 'search_descriptors', ['descriptor_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_search_descriptors_search_id'), 'search_descriptors', ['search_id'], unique=False, schema='app')
    op.create_table('user_searches',
    sa.Column('user_search_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['app.searches.search_id'], name=op.f('fk_user_searches_search_id_searches')),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.user_id'], name=op.f('fk_user_searches_user_id_users')),
    sa.PrimaryKeyConstraint('user_search_id', name=op.f('pk_user_searches')),
    sa.UniqueConstraint('user_id', 'search_id', name=op.f('uq_user_searches_user_id')),
    schema='app'
    )
    op.create_index(op.f('ix_app_user_searches_search_id'), 'user_searches', ['search_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_user_searches_user_id'), 'user_searches', ['user_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_user_searches_user_id'), table_name='user_searches', schema='app')
    op.drop_index(op.f('ix_app_user_searches_search_id'), table_name='user_searches', schema='app')
    op.drop_table('user_searches', schema='app')
    op.drop_index(op.f('ix_app_search_descriptors_search_id'), table_name='search_descriptors', schema='app')
    op.drop_index(op.f('ix_app_search_descriptors_descriptor_id'), table_name='search_descriptors', schema='app')
    op.drop_table('search_descriptors', schema='app')
    op.drop_table('users', schema='app')
    op.drop_table('searches', schema='app')
    # ### end Alembic commands ###
