"""added user studies and citations tables

Revision ID: 7e89359a7aad
Revises: 44cd6e323356
Create Date: 2018-11-06 01:19:11.612603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e89359a7aad'
down_revision = '44cd6e323356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_citations',
    sa.Column('user_citation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['pubmed.citations.citation_id'], name=op.f('fk_user_citations_citation_id_citations')),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.user_id'], name=op.f('fk_user_citations_user_id_users')),
    sa.PrimaryKeyConstraint('user_citation_id', name=op.f('pk_user_citations')),
    sa.UniqueConstraint('user_id', 'citation_id', name=op.f('uq_user_citations_user_id')),
    schema='app'
    )
    op.create_index(op.f('ix_app_user_citations_citation_id'), 'user_citations', ['citation_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_user_citations_user_id'), 'user_citations', ['user_id'], unique=False, schema='app')
    op.create_table('user_studies',
    sa.Column('user_study_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['clinicaltrials.studies.study_id'], name=op.f('fk_user_studies_study_id_studies')),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.user_id'], name=op.f('fk_user_studies_user_id_users')),
    sa.PrimaryKeyConstraint('user_study_id', name=op.f('pk_user_studies')),
    sa.UniqueConstraint('user_id', 'study_id', name=op.f('uq_user_studies_user_id')),
    schema='app'
    )
    op.create_index(op.f('ix_app_user_studies_study_id'), 'user_studies', ['study_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_user_studies_user_id'), 'user_studies', ['user_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_user_studies_user_id'), table_name='user_studies', schema='app')
    op.drop_index(op.f('ix_app_user_studies_study_id'), table_name='user_studies', schema='app')
    op.drop_table('user_studies', schema='app')
    op.drop_index(op.f('ix_app_user_citations_user_id'), table_name='user_citations', schema='app')
    op.drop_index(op.f('ix_app_user_citations_citation_id'), table_name='user_citations', schema='app')
    op.drop_table('user_citations', schema='app')
    # ### end Alembic commands ###
