"""Added synonyms tables

Revision ID: 8d5bf8037420
Revises: a0820254515f
Create Date: 2018-06-11 02:44:45.512751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5bf8037420'
down_revision = 'a0820254515f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_synonyms',
    sa.Column('concept_synonym_id', sa.BigInteger(), nullable=False),
    sa.Column('concept_id', sa.BigInteger(), nullable=False),
    sa.Column('synonym', sa.Unicode(), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['mesh.concepts.concept_id'], name=op.f('fk_concept_synonyms_concept_id_concepts')),
    sa.PrimaryKeyConstraint('concept_synonym_id', name=op.f('pk_concept_synonyms')),
    sa.UniqueConstraint('concept_id', 'md5', name=op.f('uq_concept_synonyms_concept_id')),
    schema='mesh'
    )
    op.create_index(op.f('ix_mesh_concept_synonyms_md5'), 'concept_synonyms', ['md5'], unique=False, schema='mesh')
    op.create_table('descriptor_synonyms',
    sa.Column('descriptor_synonym_id', sa.BigInteger(), nullable=False),
    sa.Column('descriptor_id', sa.BigInteger(), nullable=False),
    sa.Column('synonym', sa.Unicode(), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.ForeignKeyConstraint(['descriptor_id'], ['mesh.descriptors.descriptor_id'], name=op.f('fk_descriptor_synonyms_descriptor_id_descriptors')),
    sa.PrimaryKeyConstraint('descriptor_synonym_id', name=op.f('pk_descriptor_synonyms')),
    sa.UniqueConstraint('descriptor_id', 'md5', name=op.f('uq_descriptor_synonyms_descriptor_id')),
    schema='mesh'
    )
    op.create_index(op.f('ix_mesh_descriptor_synonyms_md5'), 'descriptor_synonyms', ['md5'], unique=False, schema='mesh')
    op.create_table('qualifier_synonyms',
    sa.Column('qualifier_synonym_id', sa.BigInteger(), nullable=False),
    sa.Column('qualifier_id', sa.BigInteger(), nullable=False),
    sa.Column('synonym', sa.Unicode(), nullable=False),
    sa.Column('md5', sa.Binary(), nullable=False),
    sa.ForeignKeyConstraint(['qualifier_id'], ['mesh.qualifiers.qualifier_id'], name=op.f('fk_qualifier_synonyms_qualifier_id_qualifiers')),
    sa.PrimaryKeyConstraint('qualifier_synonym_id', name=op.f('pk_qualifier_synonyms')),
    sa.UniqueConstraint('qualifier_id', 'md5', name=op.f('uq_qualifier_synonyms_qualifier_id')),
    schema='mesh'
    )
    op.create_index(op.f('ix_mesh_qualifier_synonyms_md5'), 'qualifier_synonyms', ['md5'], unique=False, schema='mesh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mesh_qualifier_synonyms_md5'), table_name='qualifier_synonyms', schema='mesh')
    op.drop_table('qualifier_synonyms', schema='mesh')
    op.drop_index(op.f('ix_mesh_descriptor_synonyms_md5'), table_name='descriptor_synonyms', schema='mesh')
    op.drop_table('descriptor_synonyms', schema='mesh')
    op.drop_index(op.f('ix_mesh_concept_synonyms_md5'), table_name='concept_synonyms', schema='mesh')
    op.drop_table('concept_synonyms', schema='mesh')
    # ### end Alembic commands ###
