"""removed concept_synonyms

Revision ID: 8da8e1d86fc7
Revises: 2f06a908dd0a
Create Date: 2018-06-13 08:27:40.954908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8da8e1d86fc7'
down_revision = '2f06a908dd0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mesh_concept_synonyms_md5', table_name='concept_synonyms', schema='mesh')
    op.drop_table('concept_synonyms', schema='mesh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_synonyms',
    sa.Column('concept_synonym_id', sa.BIGINT(), server_default=sa.text("nextval('mesh.concept_synonyms_concept_synonym_id_seq'::regclass)"), nullable=False),
    sa.Column('concept_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('synonym', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('md5', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['mesh.concepts.concept_id'], name='fk_concept_synonyms_concept_id_concepts'),
    sa.PrimaryKeyConstraint('concept_synonym_id', name='pk_concept_synonyms'),
    sa.UniqueConstraint('concept_id', 'md5', name='uq_concept_synonyms_concept_id'),
    schema='mesh'
    )
    op.create_index('ix_mesh_concept_synonyms_md5', 'concept_synonyms', ['md5'], unique=False, schema='mesh')
    # ### end Alembic commands ###
