"""added indices

Revision ID: a587cf021d1c
Revises: bdafc2995e2f
Create Date: 2018-10-06 07:14:07.195983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a587cf021d1c'
down_revision = 'bdafc2995e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clinicaltrials_eligibilities_maximum_age'), 'eligibilities', ['maximum_age'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_eligibilities_minimum_age'), 'eligibilities', ['minimum_age'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_study_conditions_condition_id'), 'study_conditions', ['condition_id'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_study_conditions_study_id'), 'study_conditions', ['study_id'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_study_facilities_facility_canonical_id'), 'study_facilities', ['facility_canonical_id'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_study_facilities_facility_id'), 'study_facilities', ['facility_id'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_study_facilities_study_id'), 'study_facilities', ['study_id'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_study_interventions_intervention_id'), 'study_interventions', ['intervention_id'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_study_interventions_study_id'), 'study_interventions', ['study_id'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_study_mesh_terms_mesh_term_id'), 'study_mesh_terms', ['mesh_term_id'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_clinicaltrials_study_mesh_terms_study_id'), 'study_mesh_terms', ['study_id'], unique=False, schema='clinicaltrials')
    op.create_index(op.f('ix_pubmed_article_author_affiliations_affiliation_canonical_id'), 'article_author_affiliations', ['affiliation_canonical_id'], unique=False, schema='pubmed')
    op.create_index(op.f('ix_pubmed_article_author_affiliations_affiliation_id'), 'article_author_affiliations', ['affiliation_id'], unique=False, schema='pubmed')
    op.create_index(op.f('ix_pubmed_article_author_affiliations_article_id'), 'article_author_affiliations', ['article_id'], unique=False, schema='pubmed')
    op.create_index(op.f('ix_pubmed_article_author_affiliations_author_id'), 'article_author_affiliations', ['author_id'], unique=False, schema='pubmed')
    op.create_index(op.f('ix_pubmed_citation_descriptors_qualifiers_citation_id'), 'citation_descriptors_qualifiers', ['citation_id'], unique=False, schema='pubmed')
    op.create_index(op.f('ix_pubmed_citation_descriptors_qualifiers_descriptor_id'), 'citation_descriptors_qualifiers', ['descriptor_id'], unique=False, schema='pubmed')
    op.create_index(op.f('ix_pubmed_citation_descriptors_qualifiers_qualifier_id'), 'citation_descriptors_qualifiers', ['qualifier_id'], unique=False, schema='pubmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pubmed_citation_descriptors_qualifiers_qualifier_id'), table_name='citation_descriptors_qualifiers', schema='pubmed')
    op.drop_index(op.f('ix_pubmed_citation_descriptors_qualifiers_descriptor_id'), table_name='citation_descriptors_qualifiers', schema='pubmed')
    op.drop_index(op.f('ix_pubmed_citation_descriptors_qualifiers_citation_id'), table_name='citation_descriptors_qualifiers', schema='pubmed')
    op.drop_index(op.f('ix_pubmed_article_author_affiliations_author_id'), table_name='article_author_affiliations', schema='pubmed')
    op.drop_index(op.f('ix_pubmed_article_author_affiliations_article_id'), table_name='article_author_affiliations', schema='pubmed')
    op.drop_index(op.f('ix_pubmed_article_author_affiliations_affiliation_id'), table_name='article_author_affiliations', schema='pubmed')
    op.drop_index(op.f('ix_pubmed_article_author_affiliations_affiliation_canonical_id'), table_name='article_author_affiliations', schema='pubmed')
    op.drop_index(op.f('ix_clinicaltrials_study_mesh_terms_study_id'), table_name='study_mesh_terms', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_mesh_terms_mesh_term_id'), table_name='study_mesh_terms', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_interventions_study_id'), table_name='study_interventions', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_interventions_intervention_id'), table_name='study_interventions', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_facilities_study_id'), table_name='study_facilities', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_facilities_facility_id'), table_name='study_facilities', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_facilities_facility_canonical_id'), table_name='study_facilities', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_conditions_study_id'), table_name='study_conditions', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_study_conditions_condition_id'), table_name='study_conditions', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_eligibilities_minimum_age'), table_name='eligibilities', schema='clinicaltrials')
    op.drop_index(op.f('ix_clinicaltrials_eligibilities_maximum_age'), table_name='eligibilities', schema='clinicaltrials')
    # ### end Alembic commands ###
