"""Added `affiliations_canonical` table.

Revision ID: bdafc2995e2f
Revises: df51f1d67956
Create Date: 2018-09-02 02:42:14.335349

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'bdafc2995e2f'
down_revision = 'df51f1d67956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliations_canonical',
    sa.Column('affiliation_canonical_id', sa.BigInteger(), nullable=False),
    sa.Column('google_place_id', sa.Unicode(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('google_url', sa.UnicodeText(), nullable=True),
    sa.Column('url', sa.UnicodeText(), nullable=True),
    sa.Column('address', sa.UnicodeText(), nullable=True),
    sa.Column('phone_number', sa.UnicodeText(), nullable=True),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('country', sa.Unicode(), nullable=True),
    sa.Column('administrative_area_level_1', sa.Unicode(), nullable=True),
    sa.Column('administrative_area_level_2', sa.Unicode(), nullable=True),
    sa.Column('administrative_area_level_3', sa.Unicode(), nullable=True),
    sa.Column('administrative_area_level_4', sa.Unicode(), nullable=True),
    sa.Column('administrative_area_level_5', sa.Unicode(), nullable=True),
    sa.Column('locality', sa.Unicode(), nullable=True),
    sa.Column('sublocality', sa.Unicode(), nullable=True),
    sa.Column('sublocality_level_1', sa.Unicode(), nullable=True),
    sa.Column('sublocality_level_2', sa.Unicode(), nullable=True),
    sa.Column('sublocality_level_3', sa.Unicode(), nullable=True),
    sa.Column('sublocality_level_4', sa.Unicode(), nullable=True),
    sa.Column('sublocality_level_5', sa.Unicode(), nullable=True),
    sa.Column('colloquial_area', sa.Unicode(), nullable=True),
    sa.Column('floor', sa.Unicode(), nullable=True),
    sa.Column('room', sa.Unicode(), nullable=True),
    sa.Column('intersection', sa.Unicode(), nullable=True),
    sa.Column('neighborhood', sa.Unicode(), nullable=True),
    sa.Column('post_box', sa.Unicode(), nullable=True),
    sa.Column('postal_code', sa.Unicode(), nullable=True),
    sa.Column('postal_code_prefix', sa.Unicode(), nullable=True),
    sa.Column('postal_code_suffix', sa.Unicode(), nullable=True),
    sa.Column('postal_town', sa.Unicode(), nullable=True),
    sa.Column('premise', sa.Unicode(), nullable=True),
    sa.Column('subpremise', sa.Unicode(), nullable=True),
    sa.Column('route', sa.Unicode(), nullable=True),
    sa.Column('street_address', sa.Unicode(), nullable=True),
    sa.Column('street_number', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('affiliation_canonical_id', name=op.f('pk_affiliations_canonical')),
    schema='pubmed'
    )
    op.create_index(op.f('ix_pubmed_affiliations_canonical_administrative_area_level_1'), 'affiliations_canonical', ['administrative_area_level_1'], unique=False, schema='pubmed')
    op.create_index(op.f('ix_pubmed_affiliations_canonical_country'), 'affiliations_canonical', ['country'], unique=False, schema='pubmed')
    op.create_index(op.f('ix_pubmed_affiliations_canonical_google_place_id'), 'affiliations_canonical', ['google_place_id'], unique=True, schema='pubmed')
    op.create_index(op.f('ix_pubmed_affiliations_canonical_locality'), 'affiliations_canonical', ['locality'], unique=False, schema='pubmed')
    op.add_column('affiliations', sa.Column('affiliation_canonical_id', sa.BigInteger(), nullable=True), schema='pubmed')
    op.create_foreign_key(op.f('fk_affiliations_affiliation_canonical_id_affiliations_canonical'), 'affiliations', 'affiliations_canonical', ['affiliation_canonical_id'], ['affiliation_canonical_id'], source_schema='pubmed', referent_schema='pubmed')
    op.add_column('article_author_affiliations', sa.Column('affiliation_canonical_id', sa.BigInteger(), nullable=True), schema='pubmed')
    op.create_foreign_key(op.f('fk_article_author_affiliations_affiliation_canonical_id_affiliations_canonical'), 'article_author_affiliations', 'affiliations_canonical', ['affiliation_canonical_id'], ['affiliation_canonical_id'], source_schema='pubmed', referent_schema='pubmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_article_author_affiliations_affiliation_canonical_id_affiliations_canonical'), 'article_author_affiliations', schema='pubmed', type_='foreignkey')
    op.drop_column('article_author_affiliations', 'affiliation_canonical_id', schema='pubmed')
    op.drop_constraint(op.f('fk_affiliations_affiliation_canonical_id_affiliations_canonical'), 'affiliations', schema='pubmed', type_='foreignkey')
    op.drop_column('affiliations', 'affiliation_canonical_id', schema='pubmed')
    op.drop_index(op.f('ix_pubmed_affiliations_canonical_locality'), table_name='affiliations_canonical', schema='pubmed')
    op.drop_index(op.f('ix_pubmed_affiliations_canonical_google_place_id'), table_name='affiliations_canonical', schema='pubmed')
    op.drop_index(op.f('ix_pubmed_affiliations_canonical_country'), table_name='affiliations_canonical', schema='pubmed')
    op.drop_index(op.f('ix_pubmed_affiliations_canonical_administrative_area_level_1'), table_name='affiliations_canonical', schema='pubmed')
    op.drop_table('affiliations_canonical', schema='pubmed')
    # ### end Alembic commands ###
