"""Made `facilities_canonical` table fields to nullable.

Revision ID: df51f1d67956
Revises: 29cdcb008393
Create Date: 2018-08-28 10:43:50.078238

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'df51f1d67956'
down_revision = '29cdcb008393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities_canonical', 'coordinates',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326),
               nullable=True,
               schema='clinicaltrials')
    op.alter_column('facilities_canonical', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='clinicaltrials')
    op.alter_column('facilities_canonical', 'google_url',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='clinicaltrials')
    op.alter_column('facilities_canonical', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='clinicaltrials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facilities_canonical', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='clinicaltrials')
    op.alter_column('facilities_canonical', 'google_url',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='clinicaltrials')
    op.alter_column('facilities_canonical', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='clinicaltrials')
    op.alter_column('facilities_canonical', 'coordinates',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326),
               nullable=False,
               schema='clinicaltrials')
    # ### end Alembic commands ###
